openapi: 3.0.0
info:
  title: API - CompanyService
  version: 1.0.0
  description: Documentação da API de Serviços 
servers:
  - url: http://localhost:3000/api
    description: Servidor local

tags:
  - name: CompanyService
    description: Operações relacionadas ao vínculo entre empresas e serviços

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CompanyService:
      type: object
      required:
        - id_empresa
        - id_service
      properties:
        id:
          type: integer
          example: 1
        id_empresa:
          type: integer
          example: 10
        id_service:
          type: integer
          example: 5

    CompanyServiceCreate:
      type: object
      required:
        - id_empresa
        - id_service
      properties:
        id_empresa:
          type: integer
          example: 10
        id_service:
          type: integer
          example: 5

    CompanyServiceUpdate:
      type: object
      properties:
        id_empresa:
          type: integer
          example: 12
        id_service:
          type: integer
          example: 8

    CompanyServiceList:
      type: object
      properties:
        companyServices:
          type: array
          items:
            $ref: '#/components/schemas/CompanyService'

    ApiResponseError:
      type: object
      properties:
        error:
          type: string
          example: Mensagem de erro

paths:
  /company-service:
    post:
      summary: Cria um vínculo entre empresa e serviço
      tags: [CompanyService]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyServiceCreate'
      responses:
        "201":
          description: Vínculo criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyService'
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido

    get:
      summary: Lista todos os vínculos de empresas com serviços
      tags: [CompanyService]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de vínculos cadastrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyServiceList'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Nenhum vínculo encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

  /company-service/{id}:
    get:
      summary: Busca vínculo pelo ID
      tags: [CompanyService]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do vínculo
      responses:
        "200":
          description: Vínculo encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  companyService:
                    $ref: '#/components/schemas/CompanyService'
        "400":
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Vínculo não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

    patch:
      summary: Atualiza um vínculo entre empresa e serviço
      tags: [CompanyService]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do vínculo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyServiceUpdate'
      responses:
        "200":
          description: Vínculo atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyService'
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Vínculo não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

    delete:
      summary: Remove um vínculo entre empresa e serviço
      tags: [CompanyService]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do vínculo
      responses:
        "200":
          description: Vínculo removido com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Serviço da empresa removido com sucesso.
        "400":
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Vínculo não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
