openapi: 3.0.0
info:
  title: API - Sistema de Permissões
  version: 1.0.0
  description: Documentação da API de Permissões
servers:
  - url: http://localhost:3000/api
    description: Servidor local

tags:
  - name: Permissões
    description: Operações relacionadas ao gerenciamento de permissões

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Permission:
      type: object
      required:
        - description
      properties:
        id:
          type: integer
          example: 1
        description:
          type: string
          example: Pode criar usuários

    PermissionCreate:
      type: object
      required:
        - description
      properties:
        description:
          type: string
          example: Pode criar usuários

    PermissionUpdate:
      type: object
      required:
        - description
      properties:
        description:
          type: string
          example: Pode editar relatórios

    PermissionList:
      type: object
      properties:
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'

    ApiResponseError:
      type: object
      properties:
        error:
          type: string
          example: Mensagem de erro

paths:
  /permission:
    post:
      summary: Cria uma nova permissão
      tags: [Permissões]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionCreate'
      responses:
        "201":
          description: Permissão criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido

    get:
      summary: Lista todas as permissões
      tags: [Permissões]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de permissões cadastradas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionList'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Nenhuma permissão encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

  /permission/{id}:
    get:
      summary: Busca permissão pelo ID
      tags: [Permissões]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da permissão
      responses:
        "200":
          description: Permissão encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  permission:
                    $ref: '#/components/schemas/Permission'
        "400":
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Permissão não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

    patch:
      summary: Atualiza uma permissão
      tags: [Permissões]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da permissão
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionUpdate'
      responses:
        "200":
          description: Permissão atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Permissão não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

    delete:
      summary: Remove uma permissão
      tags: [Permissões]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da permissão
      responses:
        "204":
          description: Permissão removida com sucesso
        "400":
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Permissão não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'