openapi: 3.0.0
info:
  title: API - Sistema de Permissões de Usuários
  version: 1.0.0
  description: Documentação de Permissões de Usuários
servers:
  - url: http://localhost:3000/api
    description: Servidor local

tags:
  - name: Permissões de Usuários
    description: Operações relacionadas ao gerenciamento de permissões atribuídas a usuários

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserPermission:
      type: object
      required:
        - userId
        - permissionId
      properties:
        id:
          type: integer
          example: 1
        userId:
          type: integer
          example: 10
        permissionId:
          type: integer
          example: 3

    UserPermissionCreate:
      type: object
      required:
        - userId
        - permissionId
      properties:
        userId:
          type: integer
          example: 10
        permissionId:
          type: integer
          example: 3

    UserPermissionUpdate:
      type: object
      required:
        - userId
        - permissionId
      properties:
        userId:
          type: integer
          example: 10
        permissionId:
          type: integer
          example: 3

    UserPermissionList:
      type: object
      properties:
        userPermission:
          type: array
          items:
            $ref: '#/components/schemas/UserPermission'

    ApiResponseError:
      type: object
      properties:
        error:
          type: string
          example: Mensagem de erro

    ApiResponseSuccess:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Permissão de usuário atualizada com sucesso

paths:
  /user-permissions:
    post:
      summary: Cria uma nova permissão para um usuário
      tags: [Permissões de Usuários]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPermissionCreate'
      responses:
        "201":
          description: Permissão de usuário criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermission'
        "400":
          description: Erro de validação ou permissão já existente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido

    get:
      summary: Lista todas as permissões de usuários
      tags: [Permissões de Usuários]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de permissões de usuários cadastradas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermissionList'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Nenhuma permissão de usuário encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

  /user-permissions/{id}:
    get:
      summary: Busca uma permissão de usuário pelo ID
      tags: [Permissões de Usuários]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da permissão de usuário
      responses:
        "200":
          description: Permissão de usuário encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  userPermission:
                    $ref: '#/components/schemas/UserPermission'
        "400":
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Permissão de usuário não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

    patch:
      summary: Atualiza uma permissão de usuário
      tags: [Permissões de Usuários]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da permissão de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPermissionUpdate'
      responses:
        "200":
          description: Permissão de usuário atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseSuccess'
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Permissão de usuário não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'

    delete:
      summary: Remove uma permissão de usuário
      tags: [Permissões de Usuários]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da permissão de usuário
      responses:
        "204":
          description: Permissão removida com sucesso
        "400":
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        "401":
          description: Token não fornecido ou inválido
        "404":
          description: Permissão de usuário não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
